#ifndef MAP_H
#define MAP_H

#define PIN_SAFETY_LIGHT 2
#define PERIOD_SAFETY_LIGHT 750

#define PERIOD_FIRE_DELAY 2000
#define PERIOD_FINISH_DELAY 650

#define PIN_AIM_UP 7
#define PIN_AIM_DOWN 8

#define PIN_FIRING_ACTION 3
#define PIN_ACCELERATING_RAIL 4

#endif
